spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: root2019

server:
  port: 8080 #the default port used for zuul service
eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-eureka-server.us-east-1.elasticbeanstalk.com/eureka
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    routes:
      auth-service:
        path: /uaa/** #path that will be intercepted
        url: auth-service #which url the request will e mapped to
        stripPrefix: false #if zuul should replace the "/uaa/" segment
        sensitiveHeaders:
