spring:
  datasource:
    url: jdbc:mysql://coursesdb.cljmepmpjstm.us-east-1.rds.amazonaws.com:3306/COURSES_DB
    username: admin
    password: root2019
eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-eureka-server.us-east-1.elasticbeanstalk.com/eureka
server:
  error:
    include-stacktrace: on_trace_param
