spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: password1
eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-eureka-server.us-east-1.elasticbeanstalk.com/eureka
server:
  error:
    include-stacktrace: on_trace_param
